# Generated by Django 3.2.4 on 2021-06-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='picture',
        ),
        migrations.AddField(
            model_name='entry',
            name='picture',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
