# Generated by Django 3.2.4 on 2021-07-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
