# Generated by Django 3.2.4 on 2021-07-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_alter_entry_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='blank for now', max_length=255),
            preserve_default=False,
        ),
    ]
