# Generated by Django 3.0.6 on 2020-05-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_blog_det'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=6)),
            ],
        ),
    ]
