# Generated by Django 3.0.6 on 2020-05-28 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_user_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apple',
        ),
        migrations.AddField(
            model_name='blog_det',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='practice.user_info'),
            preserve_default=False,
        ),
    ]
