# Generated by Django 3.0.6 on 2020-05-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20200528_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
